version: '3'

services:
  elasticsearch:  
    image: elasticsearch
    command: elasticsearch -Enode.name=derp -Ecluster.name=logging
    ports:
      - "9200:9200"

  logstash:  
    image: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
    - ./logstash:/etc/logstash/conf.d
    ports:
    - "5000:5000"

  kibana:  
    image: kibana
    ports:
      - "5601:5601"
